<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5</name>
   <tag></tag>
   <elementGuidId>ca0aad60-e781-4e4a-b766-a8c115c66785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='svg'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.umb-icon__inner.icon-navigation-right > ng-transclude > span > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7a5b66f2-42d1-4ae5-aef8-b1d314ed5e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>96dec48b-589e-4d6e-aa8e-6680153df7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 256 512</value>
      <webElementGuid>c161f13f-af16-4023-ad2d-68bc44082feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.fa-secondary{opacity:.4}</value>
      <webElementGuid>a335d82d-7aa8-4fee-95f6-43ecee86ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tree&quot;)/ul[@class=&quot;umb-tree&quot;]/li[1]/ul[1]/li[@class=&quot;umb-animated umb-tree-item has-children&quot;]/div[@class=&quot;umb-tree-item__inner&quot;]/button[@class=&quot;umb-tree-item__arrow umb-outline btn-reset&quot;]/span[@class=&quot;umb-icon&quot;]/span[@class=&quot;umb-icon__inner icon-navigation-right&quot;]/ng-transclude[1]/span[1]/svg[1]</value>
      <webElementGuid>b5897f63-21b2-4482-aa87-d124c52cb9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open context node for Content'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>3aceeeb7-97e3-4355-a642-84250eff9b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand child items for Trinity Market Intelligence Dashboard'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>106d967c-dcfb-4fce-a4bd-e3d9f8c6c024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trinity Market Intelligence Dashboard'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c78981ae-1f33-48e3-a9ca-b9b24535e4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = '.fa-secondary{opacity:.4}' or . = '.fa-secondary{opacity:.4}')]</value>
      <webElementGuid>6410ed00-fa3e-464e-99c1-6fbc06e931fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
