<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select employee size_UserPhone</name>
   <tag></tag>
   <elementGuidId>f93ca88b-3113-4311-a658-8dcf8f034387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserPhone-LfZM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UserPhone-LfZM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c57d7a40-ac2f-4e37-9f77-4a7d6f75670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserPhone-LfZM</value>
      <webElementGuid>1fab3c11-1e7e-48a3-ac2e-a74c84bba37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e3e25621-d912-4fa4-a0aa-7bbeaa5e95a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserPhone</value>
      <webElementGuid>14609391-967f-4be2-b79d-bcd2a2755a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1575ba9-8634-4119-9fbb-21c789d26de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41e10214-9eb2-4fc7-9438-2c5fd0b6a8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserPhone-LfZM&quot;)</value>
      <webElementGuid>73735039-dd56-4b07-bf9f-744af7a1a18c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserPhone-LfZM']</value>
      <webElementGuid>07ac1fe6-f64d-47bd-9197-02dd4a83da80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_SgVy']/div[4]/div/div/div/div/input</value>
      <webElementGuid>ebb3d3de-b713-474f-9e8e-09898bf968ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>09845099-b5f8-43a2-9b24-e3a628e0cff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserPhone-LfZM' and @type = 'tel' and @name = 'UserPhone']</value>
      <webElementGuid>82b68db8-a58b-46f2-9499-00672a868d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
