<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select your title_CompanyName</name>
   <tag></tag>
   <elementGuidId>e25f0714-bc67-47ed-9b57-afbef6a15266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyName-LCMs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyName-LCMs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dcbc86a-1be7-49d7-b9c2-90017ad9e6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyName-LCMs</value>
      <webElementGuid>05342350-22ad-4870-a0e7-f29318306fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4a3d0d1-37cb-4e13-bbe2-26506d4b94e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyName</value>
      <webElementGuid>65a32fa8-92b6-45b8-89d8-2435cd478875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57830f3e-df72-4fe0-b45c-d075b1bb160f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23eb0cca-0ffc-4461-9a91-16b02fdb9e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyName-LCMs&quot;)</value>
      <webElementGuid>618804d5-74f8-46d4-8200-c0611e634a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyName-LCMs']</value>
      <webElementGuid>7ef9971a-55a7-47c5-b843-4ead773ffdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_SgVy']/div[3]/div/div/div/div/input</value>
      <webElementGuid>ee45e67b-9d3a-46db-a1cb-5c9975fd5d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>6251adb6-12e5-4214-b04d-b221da9c751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CompanyName-LCMs' and @type = 'text' and @name = 'CompanyName']</value>
      <webElementGuid>99bccc8a-c9d3-4411-ab07-ad42236df706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
