<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>20469053-57ca-42ea-b34f-d5347a5c02b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/div[4]/div/div/form/div[4]/umb-button/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.umb-button__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>439f6e26-f7a5-4fd3-83b8-afc1363f4b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-button__content</value>
      <webElementGuid>a0f42dd5-74ff-4d48-af2d-a5cfff1c7c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'-hidden': vm.innerState !== 'init'}</value>
      <webElementGuid>7df8f526-022f-447e-bf75-3cfdcb8a56dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Login  </value>
      <webElementGuid>2d09257d-f4dc-435a-a1cd-5f370b6dcda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;umb-login-container&quot;]/div[@class=&quot;form&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/umb-button[1]/div[@class=&quot;umb-button&quot;]/button[@class=&quot;btn umb-button__button btn-success umb-button--m umb-outline&quot;]/span[@class=&quot;umb-button__content&quot;]</value>
      <webElementGuid>efb0cfae-9c16-4791-9f21-d87cfd8c58fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/div[4]/div/div/form/div[4]/umb-button/div/button/span</value>
      <webElementGuid>8bfc804c-d778-477f-94ae-5b44d83439be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide password'])[1]/following::span[7]</value>
      <webElementGuid>71da1f87-3ffb-4693-bef8-a2e21646c98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show password'])[1]/following::span[8]</value>
      <webElementGuid>67948da9-56e1-4284-b150-f253590c8f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::span[1]</value>
      <webElementGuid>62897bf6-dac2-4eb7-88e9-360952b8eadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>ce436c7d-34ad-4b59-9c45-44b82d4743c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//umb-button/div/button/span</value>
      <webElementGuid>3d110e16-210c-410a-90a8-aa2ec5852a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Login  ' or . = '  Login  ')]</value>
      <webElementGuid>3ef54dc2-dfe1-4cea-a41d-63288d6d071e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
