<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>localize_Create</name>
   <tag></tag>
   <elementGuidId>06f7d4d7-d394-402d-a489-472141407fbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/umb-property/div/ng-form/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div/button/localize</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline.umb-outline > localize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>localize</value>
      <webElementGuid>2db0899f-d056-4353-aa50-fd62887ec523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>actions_create</value>
      <webElementGuid>d59ac279-7a06-43ff-87ff-02f872b3df9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>7778647f-bdb4-4bb6-af51-a574ea85c045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentcolumn&quot;)/div[@class=&quot;umb-editor&quot;]/div[1]/div[1]/div[1]/form[@class=&quot;ng-pristine ng-valid ng-valid-required ng-valid-maxlength ng-valid-val-server-field ng-valid-val-property-msg&quot;]/div[@class=&quot;umb-panel umb-editor-wrapper&quot;]/umb-variant-content-editors[1]/div[@class=&quot;umb-split-views&quot;]/div[@class=&quot;umb-split-view&quot;]/umb-variant-content[1]/div[1]/div[@class=&quot;umb-split-view__content&quot;]/div[@class=&quot;umb-editor-container umb-panel-body umb-scrollable row-fluid&quot;]/div[@class=&quot;umb-pane&quot;]/div[@class=&quot;umb-pane-content&quot;]/div[@class=&quot;umb-editor-sub-views&quot;]/div[1]/div[@class=&quot;umb-editor-sub-view sub-view-Web Articles&quot;]/div[@class=&quot;umb-editor-sub-view__content&quot;]/div[1]/umb-property[1]/div[@class=&quot;umb-property&quot;]/ng-form[@class=&quot;ng-pristine ng-valid ng-valid-val-property-msg&quot;]/div[@class=&quot;control-group umb-control-group hidelabel umb-control-group__listview&quot;]/div[@class=&quot;umb-el-wrap&quot;]/div[@class=&quot;controls&quot;]/div[@class=&quot;umb-property-editor db&quot;]/div[1]/div[1]/div[@class=&quot;umb-property-editor umb-listview&quot;]/div[@class=&quot;row-fluid umb-listview__container&quot;]/div[@class=&quot;umb-editor-sub-header umb-editor-sub-header--&quot;]/div[@class=&quot;umb-editor-sub-header__content-left&quot;]/div[@class=&quot;umb-editor-sub-header__section&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-outline umb-outline&quot;]/localize[1]</value>
      <webElementGuid>ed91f1d5-7a21-40e3-9fde-a1500c15e634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/umb-property/div/ng-form/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div/button/localize</value>
      <webElementGuid>02c05278-3635-4e69-8b9e-65390bff9c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This item is in the Recycle Bin'])[1]/following::localize[1]</value>
      <webElementGuid>6e2542df-6e41-4e10-8f40-97dcaff4dad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[2]/preceding::localize[1]</value>
      <webElementGuid>9e9c21e0-18e5-4fba-94a8-ce89c4bcf94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>37acbe07-efec-465d-a9eb-1d4cf622a627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/localize</value>
      <webElementGuid>bf364502-04d4-433a-9c32-838f57e7fcd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//localize[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>c5fc6289-2f08-4f11-ae38-1afb0e7287f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
