<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>f0e4c755-e1ab-403f-8496-7e0f86795e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='targetedIndications']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#targetedIndications</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92dc67bb-9f74-42d0-98c8-f0d4498d7ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>model.config.multiPicker === true &amp;&amp; renderModel.length &lt; maxNumberOfItems || renderModel.length === 0 || !maxNumberOfItems</value>
      <webElementGuid>a5099ffe-29dc-4452-a848-aef9c47c081a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6deeeb8-9e5d-466e-bec7-17a576707965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-node-preview-add</value>
      <webElementGuid>4e0ab875-1b43-4a69-8f09-3b21fe1ebd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>openCurrentPicker()</value>
      <webElementGuid>6a5a5161-7604-4c90-aa33-81297888e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetedIndications</value>
      <webElementGuid>98d027a0-4b89-4826-93e5-dab0a70fd252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Targeted Indications: Add</value>
      <webElementGuid>ccf4d08c-df08-4210-9f54-d03bd1d420ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e4b91397-983f-4e60-850c-9d5210a339a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eff42300-10df-4790-8f69-a5fbf6b4bfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Add
            ...
        </value>
      <webElementGuid>817d0a19-1a51-4a18-9650-cc1c2e732aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetedIndications&quot;)</value>
      <webElementGuid>1bb03599-03cd-4005-abb0-90031a8701de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='targetedIndications']</value>
      <webElementGuid>85a75b08-770e-44b1-bebe-7316f62aebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div[3]/div[2]/umb-property[2]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/button</value>
      <webElementGuid>067f5be3-ed8c-4c68-97aa-81e95e497012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Property Actions'])[2]/following::button[1]</value>
      <webElementGuid>d602de29-d8fb-4158-b9ca-245943113aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[2]</value>
      <webElementGuid>8278c69f-20c5-4462-bdfa-fa3259b3cf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//umb-property[2]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/button</value>
      <webElementGuid>68b08b1d-fae2-4c35-90e3-10bb4706c18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'targetedIndications' and (text() = '
            Add
            ...
        ' or . = '
            Add
            ...
        ')]</value>
      <webElementGuid>c83e0297-13ef-441c-a45c-0f1ed3339559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
