<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address to the article_textbox</name>
   <tag></tag>
   <elementGuidId>d87a40ea-e8e6-4f2e-904c-cf4d8e8962c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#urlAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c54d088-c5eb-40af-a341-882fe174fec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3187679e-a6f6-4bda-b469-e78bdcfb834d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlAddress</value>
      <webElementGuid>7f4d3d78-625c-4bf6-a45d-60d78fb73682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>90830117-19bd-466c-b33c-f8c38ea193fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.value</value>
      <webElementGuid>b5f38c61-efd3-4d53-9896-646d94bd442b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-property-editor umb-textstring textstring ng-pristine ng-untouched ng-valid-val-server ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>441287a7-169c-42b4-b63f-b48fd440843b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>b0855471-3bf0-4ec9-911c-00c0e95b4a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>model.validation.mandatory</value>
      <webElementGuid>5cc9a23d-3e8d-4fc7-9a28-f347b8513e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be6a8b3e-5280-4830-85ae-5b422424928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21d1d26c-ea4a-4fd9-9a4c-bf83bd8c1211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5378d22-2cca-4d0a-b47a-d3e884b4bbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>change()</value>
      <webElementGuid>0fcd603c-94cf-4b39-a6a8-15bafe42eb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>060d6ab6-e1f3-4d04-abab-0090bc821fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b46af5c1-1d9b-4690-98c6-5efe88cd4e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlAddress&quot;)</value>
      <webElementGuid>c443db42-bee9-4f8e-80ad-04585b7b12db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlAddress']</value>
      <webElementGuid>8873027e-fa11-4931-a56e-aef6636a0bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div/div/umb-property[3]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/input</value>
      <webElementGuid>e7a4cb92-8061-40f0-b813-4b0f6c87f242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ng-form/input</value>
      <webElementGuid>27a0a683-93a9-4379-8759-eb0656021fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'urlAddress' and @name = 'textbox']</value>
      <webElementGuid>25a79c8d-05e4-46c0-a98f-3c82ee155444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
