<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date the article was published_datepicker</name>
   <tag></tag>
   <elementGuidId>9600cbec-c0ff-49e3-96dd-03cf21105c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePublished']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datePublished</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec9a2fd3-767a-47b2-baa3-aa3b496f2a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16e5dfe0-f3d6-4f5c-a7af-f879254b009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>fa472974-42d4-4a16-bf98-832019824e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePublished</value>
      <webElementGuid>b22fb421-2e6b-4b6d-88de-16c5883b8cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.datetimePickerValue</value>
      <webElementGuid>cea86003-a848-4ccb-9da2-d8fdb0cd2c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>inputChanged()</value>
      <webElementGuid>c50cf4c0-16e0-49c3-a9c8-3b7ecf6d6b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>model.validation.mandatory</value>
      <webElementGuid>43ca080b-8a39-458f-afa7-92a72ff2cd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>a0949cf7-995a-4c81-a963-c074393351cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepickerinput ng-pristine ng-untouched ng-valid-val-server ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>fbaae49f-b092-4c85-8705-74f4ef6bc90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>567715ad-89e9-488f-bd99-c9083885a9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9206ec6d-e425-469f-bfd0-677541145a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58093fe3-2bfd-45b9-8f13-d3430977b5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePublished&quot;)</value>
      <webElementGuid>99917801-4ed3-4740-bcd9-30e642fa8246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePublished']</value>
      <webElementGuid>285b25bf-dc65-4dbf-b905-e64a55d5b73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepickerdatePublished']/umb-date-time-picker/ng-transclude/div/input</value>
      <webElementGuid>bf290772-8dec-4238-a7ee-732c6031d26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d12ddc0b-b6e2-4a2e-8083-ad3c3980c64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepicker' and @id = 'datePublished']</value>
      <webElementGuid>a22afe4a-2cf0-4324-8ad9-f6eb976e36b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
