<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Web Article Name_headerName</name>
   <tag></tag>
   <elementGuidId>9e0568ca-ffe6-4e0a-a3e5-d875bdedff52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headerName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48022526-883f-4000-bac4-dbe3d6c6333b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element</name>
      <type>Main</type>
      <value>editor-name-field</value>
      <webElementGuid>8b69b1a9-615d-42ea-bfc9-b2658c03f70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e8194f4-7ce5-4f5f-adda-02e2225b546c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-editor-header__name-input ng-untouched ng-valid-maxlength ng-valid-val-server-field ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>24ac60c7-e270-48a4-8d62-74998b90b57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>7706f684-4425-4891-9393-8f44f1f26eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>headerName</value>
      <webElementGuid>448499c5-0fb7-49b4-9440-e175ddb20f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerName</value>
      <webElementGuid>eaa88502-6cb1-4cc0-876f-1266a439a9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>db9f2f4f-57b6-4f9e-b5e6-8455762a2c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'name-is-empty': $parent.name===null || $parent.name===''}</value>
      <webElementGuid>61e85042-bfd4-46a3-93bd-c3c4f048dbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>nameDisabled</value>
      <webElementGuid>58921c90-33ca-45a3-92b5-7e7cc6b389e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>nameReadonly</value>
      <webElementGuid>379c8cb2-9379-4caf-a177-57b23ff9c97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focus-on-filled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06455626-f8b5-48ea-9d44-8123aea867ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server-field</name>
      <type>Main</type>
      <value>Variants[0].Name</value>
      <webElementGuid>06d30479-7a64-4a52-9f45-9f6ac37e6a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59493230-6318-4a6f-b52f-dd3e4eded23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>280080db-9b9d-4d68-9a9e-00b2ae18ad9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3df9b0cf-c03e-4aae-ad8f-824a3c614ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>ad4c443d-c363-4c1d-b538-c09a29c7ce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a name...</value>
      <webElementGuid>865eb4d1-3a76-43b2-89d6-1b27d81f738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerName&quot;)</value>
      <webElementGuid>5e4753bd-089c-4e66-a7b7-059d8908a9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headerName']</value>
      <webElementGuid>79e93a48-350e-4522-b7dd-fcef3c28e37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nameField']/div[2]/ng-form/input</value>
      <webElementGuid>727bc85a-5740-4dc0-b2ec-061932308947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fd3834d0-0260-4e30-9f47-a816adc46541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'headerName' and @id = 'headerName' and @placeholder = 'Enter a name...']</value>
      <webElementGuid>8a064efa-9337-46d4-8987-c3b83cb77f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
