<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit</name>
   <tag></tag>
   <elementGuidId>3ed8a44b-3a29-4a58-8db6-f48ff9b3086a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='umbracoMainPageBody']/div[4]/div/div/div/form/div/div[3]/div/div/umb-button[2]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>umb-button[type=&quot;button&quot;] > div.umb-button > button.btn.umb-button__button.btn-success.umb-button--.umb-outline > span.umb-button__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34fe5cf3-64d0-4be9-baea-f988bf89bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-button__content</value>
      <webElementGuid>03edab80-e8bb-4c02-844f-49354f8a4188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'-hidden': vm.innerState !== 'init'}</value>
      <webElementGuid>3fe7423b-1e10-4ebf-8663-da4c3d6938ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Submit  </value>
      <webElementGuid>fb61a887-ecb1-4231-8086-ebac733e8eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;umbracoMainPageBody&quot;)/div[@class=&quot;umb-editors&quot;]/div[@class=&quot;umb-editor umb-editor--small umb-editor--infiniteMode umb-editor--n1 umb-editor--level1&quot;]/div[1]/div[1]/form[@class=&quot;ng-pristine ng-valid ng-valid-val-server-field ng-valid-required ng-valid-maxlength&quot;]/div[@class=&quot;umb-panel umb-editor-wrapper&quot;]/div[@class=&quot;umb-editor-footer&quot;]/div[@class=&quot;umb-editor-footer-content&quot;]/div[@class=&quot;umb-editor-footer-content__right-side&quot;]/umb-button[2]/div[@class=&quot;umb-button&quot;]/button[@class=&quot;btn umb-button__button btn-success umb-button-- umb-outline&quot;]/span[@class=&quot;umb-button__content&quot;]</value>
      <webElementGuid>f501d0e9-a168-4a10-b031-7ea25129c222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='umbracoMainPageBody']/div[4]/div/div/div/form/div/div[3]/div/div/umb-button[2]/div/button/span</value>
      <webElementGuid>01313d81-0d15-4f99-aede-394f6f0a3096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::span[14]</value>
      <webElementGuid>36414215-fca3-4653-9731-e27981bc8731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::span[5]</value>
      <webElementGuid>da9a9950-2767-406e-8f3e-c48e873307dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/preceding::span[6]</value>
      <webElementGuid>efbc8a43-1d43-4367-8f95-64a64761356c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>48ed77c9-8195-44ab-b0a5-0387b1458b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//umb-button[2]/div/button/span</value>
      <webElementGuid>acd538ea-5bda-480d-81bc-cde9093dc080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Submit  ' or . = '  Submit  ')]</value>
      <webElementGuid>e0079a98-86d6-4ba1-920b-0245044e1acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
