<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_None_umb-form-check__check</name>
   <tag></tag>
   <elementGuidId>53a1456a-ad57-4573-91c7-59c8188de2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div[3]/div[2]/umb-property/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/ul/li[2]/umb-radiobutton/label/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>651a5f6b-d13d-4dfc-b8b1-92c44ad1a1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-form-check__check</value>
      <webElementGuid>5ce48b73-bc29-4ce5-9c02-f0fa6c49d991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentcolumn&quot;)/div[@class=&quot;umb-editor&quot;]/div[1]/div[1]/div[1]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-val-server-field ng-valid-val-property-msg ng-invalid-min-count ng-valid-max-count ng-valid-val-server ng-dirty ng-valid-parse ng-valid-picker-error&quot;]/div[@class=&quot;umb-panel umb-editor-wrapper&quot;]/umb-variant-content-editors[1]/div[@class=&quot;umb-split-views&quot;]/div[@class=&quot;umb-split-view&quot;]/umb-variant-content[1]/div[1]/div[@class=&quot;umb-split-view__content&quot;]/div[@class=&quot;umb-editor-container umb-panel-body umb-scrollable row-fluid&quot;]/div[@class=&quot;umb-pane&quot;]/div[@class=&quot;umb-pane-content&quot;]/div[@class=&quot;umb-editor-sub-views&quot;]/div[1]/div[@class=&quot;umb-editor-sub-view sub-view-Content&quot;]/div[@class=&quot;umb-editor-sub-view__content&quot;]/div[@class=&quot;form-horizontal&quot;]/div[1]/ng-form[@class=&quot;ng-valid-val-property-msg ng-invalid ng-invalid-required ng-invalid-min-count ng-valid-max-count ng-valid-val-server ng-valid-maxlength ng-valid-picker-error ng-dirty ng-valid-parse&quot;]/div[@class=&quot;umb-group-panel&quot;]/div[@class=&quot;umb-group-panel__content&quot;]/umb-property[1]/div[@class=&quot;umb-property&quot;]/ng-form[@class=&quot;ng-pristine ng-valid-val-property-msg ng-invalid ng-invalid-required&quot;]/div[@class=&quot;control-group umb-control-group&quot;]/div[@class=&quot;umb-el-wrap&quot;]/div[@class=&quot;controls&quot;]/div[@class=&quot;umb-property-editor db&quot;]/div[1]/div[1]/div[@class=&quot;umb-property-editor umb-radiobuttons&quot;]/ng-form[@class=&quot;ng-pristine ng-invalid ng-invalid-required&quot;]/ul[@class=&quot;unstyled&quot;]/li[2]/umb-radiobutton[1]/label[@class=&quot;radio umb-form-check umb-form-check--radiobutton&quot;]/span[@class=&quot;umb-form-check__symbol&quot;]/span[@class=&quot;umb-form-check__state&quot;]/span[@class=&quot;umb-form-check__check&quot;]</value>
      <webElementGuid>50be6ecf-b84a-4975-8b81-926d00e6e311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div[3]/div[2]/umb-property/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/ul/li[2]/umb-radiobutton/label/span/span/span</value>
      <webElementGuid>3761dfbc-4f65-43c0-8d1f-f4a10efea081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/umb-radiobutton/label/span/span/span</value>
      <webElementGuid>0929c1d5-e4cc-4def-95c9-b753beb5d313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
