<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DDS TERRA_input-text ng-untouched ng-_399ea0</name>
   <tag></tag>
   <elementGuidId>c718fb07-c854-4fd9-a3c6-de3198af357b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-text.ng-untouched.ng-valid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e09cbe6-3114-45eb-a298-5f122342e48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>a2a6e3ae-8096-425f-8c4d-406a9846b851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your password</value>
      <webElementGuid>6f0f6b8f-a0bf-48cf-9aa8-c0d00fad812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>e40c16bd-181a-4809-88b8-b28b7e8f6a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>terrasso@123</value>
      <webElementGuid>d32d64a6-7669-4928-b704-b6b12ee0b6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed5b2b65-e77e-445f-af1a-e635d09fbaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[1]/app-login-page[1]/div[@class=&quot;bg&quot;]/div[@class=&quot;grid-container-two&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;input_field_container&quot;]/div[3]/input[@class=&quot;input-text ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>90980b33-d790-420f-a851-638503d13327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>67fd37eb-a5e1-4364-975d-708f5235c6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>1478018b-ee95-453c-be9a-0bef72779712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input your password' and @type = 'password']</value>
      <webElementGuid>fa3960fc-7aa6-4b82-9bb6-60a5a30afab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
