<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add item</name>
   <tag></tag>
   <elementGuidId>ce52ea84-d074-42e8-8d1c-2410fa962d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-13']/nz-option-container/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.new-db-add-item.ant-btn.ant-btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2f01fbc-f2f1-42f3-a6d6-4df831b7f190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nztype</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>5501a50a-9046-4220-80ac-3e94e6170fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-db-add-item ant-btn ant-btn-primary</value>
      <webElementGuid>af94daaf-9f5f-4cbb-8fe4-80bd6e08f39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add item </value>
      <webElementGuid>3a564268-c011-44d5-a6f0-f6fbf2c0ffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-13&quot;)/nz-option-container[@class=&quot;ng-tns-c120-189 ng-trigger ng-trigger-slideMotion ant-select-dropdown ng-star-inserted ant-select-dropdown-placement-topLeft&quot;]/div[1]/div[@class=&quot;new-db-container ng-star-inserted&quot;]/button[@class=&quot;new-db-add-item ant-btn ant-btn-primary&quot;]</value>
      <webElementGuid>90eb7d1d-3765-4fae-aa82-c49be5d7ce4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/nz-option-container/div/div/button</value>
      <webElementGuid>18f00dcc-67d5-4a53-993d-37555379faa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PURPLELABS_CLAIMS_DATA'])[1]/following::button[1]</value>
      <webElementGuid>71a1389d-f036-4385-84e4-2f431d29b551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PREPARED_DATA'])[1]/following::button[1]</value>
      <webElementGuid>5b2f1866-8fa3-4285-9376-feb5d02d9718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-container/div/div/button</value>
      <webElementGuid>91e54e42-b7a9-4ade-bf8c-d9bdcf5e656d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add item ' or . = ' Add item ')]</value>
      <webElementGuid>2871e362-23f7-445b-a54b-a7a58855a3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
