<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_amazon_sftp_connection_cloudqa</name>
   <tag></tag>
   <elementGuidId>2cb525a7-14d2-4fa7-afbf-aa617d406d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='amazon_sftp_connection_cloudqa']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ng-star-inserted.ant-select-item-option-active > div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22687063-2d38-4ebb-8c6e-895ed7b29b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>ee8e53de-c6c8-4d4b-ba21-52950b0558b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>amazon_sftp_connection_cloudqa</value>
      <webElementGuid>0a2c2f7e-91f6-4b19-90f5-9cd82465f2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-2&quot;)/nz-option-container[@class=&quot;ng-tns-c120-171 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ant-select-dropdown ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ng-star-inserted ant-select-item-option-active&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>9954e0a2-4a83-4967-bc2d-0312580e1a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[19]/div</value>
      <webElementGuid>22e42909-de96-4eb3-9366-55bd91e45fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='redshift_connection_test'])[1]/following::div[1]</value>
      <webElementGuid>78042a36-a086-41e0-985e-5b029612ed45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon_SFTP_connection_keybased'])[1]/following::div[2]</value>
      <webElementGuid>aa6b9960-ac2c-478a-9e95-3d129c66f4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amanzon_s3_connection_cloudqa'])[1]/preceding::div[1]</value>
      <webElementGuid>cf7b1dce-1581-465f-8e6d-1ee8e7574f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazons3_role_based'])[1]/preceding::div[2]</value>
      <webElementGuid>82775055-2b05-478f-9b6e-fd0890d2a24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='amazon_sftp_connection_cloudqa']/parent::*</value>
      <webElementGuid>c5cf6f5e-e6d4-4d12-b5ee-cf33dfe16ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item[19]/div</value>
      <webElementGuid>b6db36e9-21a2-4195-b8ea-373dc2ee75bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'amazon_sftp_connection_cloudqa' or . = 'amazon_sftp_connection_cloudqa')]</value>
      <webElementGuid>b7ffe0eb-f52e-4fd2-b5d8-e56f0fa71342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
