<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AWS</name>
   <tag></tag>
   <elementGuidId>e558f1d4-a76a-40fb-a5de-7d93eac8f7e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/nz-modal-container/div/div/div[2]/div/div/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17aca28b-91f2-4781-aead-0a50330b38fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name-div</value>
      <webElementGuid>7a251b86-4d72-461a-b1d1-7ce4e279be62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AWS </value>
      <webElementGuid>05f06a8b-bd26-4a5c-ae07-607258da63fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/nz-modal-container[@class=&quot;ng-tns-c66-197 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c66-197&quot;]/div[@class=&quot;ant-modal-content ng-tns-c66-197&quot;]/div[@class=&quot;ant-modal-body ng-tns-c66-197&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;gutter-row ant-col ant-col-8 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;conn-item ant-dropdown-trigger ng-star-inserted&quot;]/div[@class=&quot;name-div&quot;]</value>
      <webElementGuid>16bff4cb-e649-43bb-9ad7-1cb4a68d4cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nz-modal-container/div/div/div[2]/div/div/div[3]/div/div/div</value>
      <webElementGuid>25826426-62fa-48b7-8c58-74a92029aa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesforce'])[1]/following::div[4]</value>
      <webElementGuid>82341fdd-c2fe-4463-a025-16d38fababa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RDBMS'])[1]/following::div[8]</value>
      <webElementGuid>bc4b4925-7fa5-4653-bfcb-d5c94690a478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft Azure'])[1]/preceding::div[1]</value>
      <webElementGuid>06a0c6ed-f59d-4f5d-b554-3f9d5f4d70df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Cloud'])[1]/preceding::div[5]</value>
      <webElementGuid>d7ea6a40-f802-42d9-b73e-ab4378dcd7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AWS']/parent::*</value>
      <webElementGuid>bf9fa76e-77b4-4322-aaff-2921542f4853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>50c5bf30-7e88-4286-99c7-55d44dce94b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' AWS ' or . = ' AWS ')]</value>
      <webElementGuid>b519d3a9-0fde-4fc4-8b34-049bc5698ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
