<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Snowflake_Connection_Cloudqa</name>
   <tag></tag>
   <elementGuidId>e8e1bba1-0d95-4f56-b068-4ba8f98756d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-10']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-option-item.ant-select-item.ant-select-item-option.ng-star-inserted.ant-select-item-option-active > div.ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab69de79-4aa1-4dd2-b2ed-1903abc52db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>bfc4617c-764e-4527-b831-5843f8db67d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Snowflake_Connection_Cloudqa</value>
      <webElementGuid>60b4b285-ddcb-4546-9773-6f1495904d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-10&quot;)/nz-option-container[@class=&quot;ng-tns-c120-182 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ant-select-dropdown ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ng-star-inserted ant-select-item-option-active&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>8804dc01-7cda-42a1-8c1d-79b707d39656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[3]/div</value>
      <webElementGuid>1f592e2f-c3a5-4404-bb91-ac0fb2dfa95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='snowflake_connection_test'])[1]/following::div[1]</value>
      <webElementGuid>96aa9853-ff86-48fa-b9a5-b38e7b4105d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='snowflake_uat'])[1]/following::div[2]</value>
      <webElementGuid>82b980b6-94d5-4c38-9d21-5427f433ceac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Snowflake_Connection_Cloudqa']/parent::*</value>
      <webElementGuid>134664cf-f9e9-4a43-93f4-41261b0d3855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item[3]/div</value>
      <webElementGuid>249cf3ce-11ec-458e-afa5-465cc0cd0546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Snowflake_Connection_Cloudqa' or . = 'Snowflake_Connection_Cloudqa')]</value>
      <webElementGuid>6a1ce68c-18f5-4ac4-92d7-80e765447472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
