<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>12024bf7-6a86-4d41-9646-b084674fcf7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='plus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;plus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e5173d1-0da0-40f2-bb58-6fb83b87e109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/image/plus.svg</value>
      <webElementGuid>158b99d3-b19f-47e9-98bd-5076814e7f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>8310a93b-fa3a-4bda-9b8a-a01954bae37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-workflow-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-1 ant-row&quot;]/div[@class=&quot;flot-right ant-col ant-col-5 ant-col-offset-13&quot;]/a[1]/div[@class=&quot;custom-add-btn ant-row&quot;]/div[@class=&quot;icon-div ant-col ant-col-4&quot;]/img[1]</value>
      <webElementGuid>7803a4cb-5f95-4058-9329-c55bc13f0ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='plus']</value>
      <webElementGuid>38e14554-3991-41c3-92f8-01a807837e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/img</value>
      <webElementGuid>74653ca4-73a4-47b9-939c-41ba6c5275b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/image/plus.svg' and @alt = 'plus']</value>
      <webElementGuid>f8e1eeda-c423-4bbe-afdd-97f675ff49b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
