<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>5628c6b0-4a9d-40a8-9525-39f88757dfb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='folder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;folder&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f7eb5e7a-0458-47c8-9f13-9a177811d6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/image/folder.png</value>
      <webElementGuid>4282e345-e58e-4472-bd43-e0213290e143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>folder</value>
      <webElementGuid>67906c05-d55d-44e6-a782-221c05d1ec84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/app-source-connection-mapping[1]/div[@class=&quot;connection form ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row&quot;]/nz-form-control[@class=&quot;ng-tns-c181-201 ant-form-item-control ant-col ant-col-6 ant-col-xs-24 ant-col-sm-6 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c181-201&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c181-201&quot;]/button[@class=&quot;ng-tns-c181-201 ant-btn ant-btn-link ant-tooltip-open&quot;]/img[1]</value>
      <webElementGuid>9555842e-98ce-426f-b3f8-4024ecbc87bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='folder']</value>
      <webElementGuid>b1d25dac-0163-4c9c-8cee-cdf749cf513b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-form-item[2]/nz-form-control[2]/div/div/button/img</value>
      <webElementGuid>c8113d0a-b656-46c1-a319-c2ecf2c7f87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/image/folder.png' and @alt = 'folder']</value>
      <webElementGuid>b40c1f75-d5bc-4f4c-94a9-c13e0d979b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
