<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PURPLELABS_CLAIMS_DATA_mb-1 ant-input</name>
   <tag></tag>
   <elementGuidId>ebf364aa-00ef-4a53-a15f-7bae32e318b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mb-1.ant-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>436b5280-cec8-4cc8-9bd0-b30b26bcacbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d712396-771e-4f73-ac41-27c00cd1ac03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add target table</value>
      <webElementGuid>111d92fb-14d9-4e6e-840a-bf47a001e95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1 ant-input</value>
      <webElementGuid>b676be1b-01e0-400c-a1af-9082e961dbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-13&quot;)/nz-option-container[@class=&quot;ng-tns-c120-189 ng-trigger ng-trigger-slideMotion ant-select-dropdown ng-star-inserted ant-select-dropdown-placement-topLeft&quot;]/div[1]/div[@class=&quot;new-db-container ng-star-inserted&quot;]/input[@class=&quot;mb-1 ant-input&quot;]</value>
      <webElementGuid>8a801332-7b82-4a8f-a142-83fbcf81c81f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>7d62d3ed-81a0-42ea-a6e5-f815eedad940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/nz-option-container/div/div/input</value>
      <webElementGuid>3478d092-e23b-4781-b51c-9f19646cabaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-container/div/div/input</value>
      <webElementGuid>4defda67-1218-4543-9097-9cb034088fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Add target table']</value>
      <webElementGuid>13e6da3f-18bc-4b6a-935e-d0a57d0887b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
