<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ant-select-selection-search-input ng_567348_1_2</name>
   <tag></tag>
   <elementGuidId>e95bf44f-a40a-4f47-95da-30126d91ec75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nz-form-item[2]/nz-form-control/div/div/nz-select/nz-select-top-control/nz-select-search/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-select-search.ng-tns-c119-187.ant-select-selection-search.ng-star-inserted > input.ant-select-selection-search-input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b444e672-e0fc-4c23-891b-80a888ca5ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f52b61e9-e08b-4e66-8b51-cec953493bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>87633f79-7734-47c7-af47-d6d45b36ddf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ce97f015-0e16-4531-a16c-76610fa2ebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout ng-star-inserted&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/div[1]/nz-content[@class=&quot;nz_content ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-add-workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered ng-star-inserted&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/app-connection-mapping[1]/div[@class=&quot;connection form ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row ng-star-inserted&quot;]/nz-form-control[@class=&quot;ng-tns-c181-185 ant-form-item-control ant-col ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c181-185&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c181-185&quot;]/nz-select[@class=&quot;ng-tns-c120-186 ng-tns-c181-185 ant-select ant-select-show-arrow ant-select-show-search ant-select-single ng-untouched ng-pristine ng-valid ng-star-inserted cdk-focused cdk-mouse-focused ant-select-focused&quot;]/nz-select-top-control[@class=&quot;ng-tns-c120-186 ng-tns-c119-187 ant-select-selector ng-star-inserted&quot;]/nz-select-search[@class=&quot;ng-tns-c119-187 ant-select-selection-search ng-star-inserted&quot;]/input[@class=&quot;ant-select-selection-search-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ea1d02d3-59d7-4fb6-8c97-5825e5affe93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-form-item[2]/nz-form-control/div/div/nz-select/nz-select-top-control/nz-select-search/input</value>
      <webElementGuid>12ceebbc-12cb-4d1b-88e6-10ead84b7751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
