<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CSV</name>
   <tag></tag>
   <elementGuidId>a654303e-10d1-49b5-94d1-997283738b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-5']/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-dropdown-menu-item.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aeefe192-452c-4f30-9fac-73c0fa2c3401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-dropdown-menu-item ng-star-inserted</value>
      <webElementGuid>88f62637-99cf-419a-8232-85ab719d74dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CSV </value>
      <webElementGuid>b93cecfb-7c4d-4945-86ae-2a4245458dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/div[@class=&quot;ant-dropdown ng-tns-c110-206 ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/ul[@class=&quot;custom-dropdown ant-dropdown-menu ant-dropdown-menu-root ant-dropdown-menu-light ant-dropdown-menu-vertical ng-tns-c110-206&quot;]/li[@class=&quot;ant-dropdown-menu-item ng-star-inserted&quot;]</value>
      <webElementGuid>7a76f10f-b260-4fc6-bc44-af487520ab38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/div/ul/li</value>
      <webElementGuid>6da23f10-0b34-4ad8-ba67-28a5ad2bd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unstructured Files'])[1]/following::li[1]</value>
      <webElementGuid>c57c1cb2-e198-439d-8f9f-4e69c1be9254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semi Structured'])[1]/following::li[1]</value>
      <webElementGuid>037e2d24-a66e-4191-826b-e9a213453b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSV'])[1]/preceding::li[1]</value>
      <webElementGuid>8d9c4ae3-ee98-49f5-901f-bcfb857c86bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TSV'])[1]/preceding::li[2]</value>
      <webElementGuid>16b47a9d-3b03-4ea2-8d01-450eb0234b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CSV']/parent::*</value>
      <webElementGuid>e8c49530-733d-43e3-b873-bfae247971b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li</value>
      <webElementGuid>e65b3795-2e44-4453-930e-127ce22b60d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' CSV ' or . = ' CSV ')]</value>
      <webElementGuid>14d499b2-6227-448b-a883-00d917791b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
