<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nz-tree-node-switcher_test_ant-tree-switche_7e597d</name>
   <tag></tag>
   <elementGuidId>0c28a983-3097-4b1a-8397-f21ad0ae3dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='test_data'])[1]/preceding::nz-tree-node-switcher[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-tree-node-switcher</value>
      <webElementGuid>fb3eb7a8-ec8a-4d7e-bb2c-ba4add55e9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tree-switcher ant-tree-switcher_close ng-star-inserted</value>
      <webElementGuid>d71ba0e6-e0f2-42dc-97cc-c4a38f40f9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/nz-modal-container[@class=&quot;ng-tns-c66-215 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c66-215&quot;]/div[@class=&quot;ant-modal-content ng-tns-c66-215&quot;]/div[@class=&quot;ant-modal-body ng-tns-c66-215&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;tree-container ng-star-inserted&quot;]/nz-tree[@class=&quot;nz_tree ng-tns-c305-216 ant-tree ant-tree-icon-hide ant-tree-block-node ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c305-216&quot;]/div[@class=&quot;ng-tns-c305-216&quot;]/div[@class=&quot;ng-tns-c305-216 ng-trigger ng-trigger-treeCollapseMotion ng-star-inserted&quot;]/nz-tree-node[@class=&quot;ng-tns-c305-216 ant-tree-treenode ant-tree-treenode-switcher-close ng-star-inserted&quot;]/nz-tree-node-switcher[@class=&quot;ant-tree-switcher ant-tree-switcher_close ng-star-inserted&quot;]</value>
      <webElementGuid>81f839f3-afd7-48c9-b11f-783fdc686ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/nz-modal-container/div/div/div[2]/div/div[2]/nz-tree/div[2]/div/div/nz-tree-node[61]/nz-tree-node-switcher</value>
      <webElementGuid>2626008d-1e18-41dc-a716-e90a11f72299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::nz-tree-node-switcher[1]</value>
      <webElementGuid>ccc5ce0c-6c41-418c-bc73-a864dde45d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tempfiles'])[1]/following::nz-tree-node-switcher[2]</value>
      <webElementGuid>996a1315-bdea-4510-ba7f-c7387ecbaf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test_data'])[1]/preceding::nz-tree-node-switcher[1]</value>
      <webElementGuid>0fd7ffb7-7e5e-4f5c-8d46-619e559a99a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test_data_unzip'])[1]/preceding::nz-tree-node-switcher[2]</value>
      <webElementGuid>edd74c9d-dcf2-40fe-b556-cb762d16dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-tree-node[61]/nz-tree-node-switcher</value>
      <webElementGuid>796547f4-5b90-42b3-ae8a-e431ff3824ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
