<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Web Article</name>
   <tag></tag>
   <elementGuidId>9e95ba9b-7ad0-47f2-8264-504b1ecee66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[75]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline.umb-outline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b4e4a91-b4fa-4a02-ad1b-1b26dbb4d350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>458c6bda-d199-4c26-8de0-3d5fc341700a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline umb-outline</value>
      <webElementGuid>b2789e92-0aed-44ae-aa94-ec2a251762c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>createBlank(entityType,listViewAllowedTypes[0].alias)</value>
      <webElementGuid>770d74b9-fb03-4c25-ba5c-fb2bc67688f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                           Create Web Article
                       </value>
      <webElementGuid>94eaf084-a9a0-4996-9098-294862f4d9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentcolumn&quot;)/div[@class=&quot;umb-editor&quot;]/div[1]/div[1]/div[1]/form[@class=&quot;ng-pristine ng-valid ng-valid-required ng-valid-maxlength ng-valid-val-server-field ng-valid-val-property-msg&quot;]/div[@class=&quot;umb-panel umb-editor-wrapper&quot;]/umb-variant-content-editors[1]/div[@class=&quot;umb-split-views&quot;]/div[@class=&quot;umb-split-view&quot;]/umb-variant-content[1]/div[1]/div[@class=&quot;umb-split-view__content&quot;]/div[@class=&quot;umb-editor-container umb-panel-body umb-scrollable row-fluid&quot;]/div[@class=&quot;umb-pane&quot;]/div[@class=&quot;umb-pane-content&quot;]/div[@class=&quot;umb-editor-sub-views&quot;]/div[1]/div[@class=&quot;umb-editor-sub-view sub-view-Web Articles&quot;]/div[@class=&quot;umb-editor-sub-view__content&quot;]/div[1]/umb-property[1]/div[@class=&quot;umb-property&quot;]/ng-form[@class=&quot;ng-pristine ng-valid ng-valid-val-property-msg&quot;]/div[@class=&quot;control-group umb-control-group hidelabel umb-control-group__listview&quot;]/div[@class=&quot;umb-el-wrap&quot;]/div[@class=&quot;controls&quot;]/div[@class=&quot;umb-property-editor db&quot;]/div[1]/div[1]/div[@class=&quot;umb-property-editor umb-listview&quot;]/div[@class=&quot;row-fluid umb-listview__container&quot;]/div[@class=&quot;umb-editor-sub-header umb-editor-sub-header--&quot;]/div[@class=&quot;umb-editor-sub-header__content-left&quot;]/div[@class=&quot;umb-editor-sub-header__section&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-outline umb-outline&quot;]</value>
      <webElementGuid>40d10bad-aff6-4bb6-903a-8ad0c2c08b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[75]</value>
      <webElementGuid>b941ea12-ba83-4c81-832d-13ca81402ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/umb-property/div/ng-form/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>53d03838-0b67-402c-b0e4-deadde222425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This item is in the Recycle Bin'])[1]/following::button[1]</value>
      <webElementGuid>44ffdf70-bee8-4c8a-98ad-479e0627bbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web Article']/parent::*</value>
      <webElementGuid>5c993fc9-fccd-42cd-b475-539d5ed3fc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>249011f3-21bd-48eb-bcc3-bae60250ab0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                           Create Web Article
                       ' or . = '
                           Create Web Article
                       ')]</value>
      <webElementGuid>c47081bb-b5fb-43a6-a3d2-56242721aa03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
