<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>c2c144a4-f0df-4003-8606-5f577d10be01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='targetedIndications']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#targetedIndications</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fd082ee-40dd-4301-9fe9-438e643b3f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>model.config.multiPicker === true &amp;&amp; renderModel.length &lt; maxNumberOfItems || renderModel.length === 0 || !maxNumberOfItems</value>
      <webElementGuid>fca63348-6e8a-4fae-b01b-9dd42535e001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1aed3cbe-8bc8-4ac8-aa8d-604fc05317e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-node-preview-add</value>
      <webElementGuid>0acc622f-9322-4957-bb84-d14488d1e010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>openCurrentPicker()</value>
      <webElementGuid>429c799e-edcf-408b-9e86-2aac1bdce6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetedIndications</value>
      <webElementGuid>72623275-4516-46e5-97a1-bb102dfc5474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Targeted Indications: Add</value>
      <webElementGuid>bcd4d075-410f-46c8-996d-4d3693a9d423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>21fe9e6c-708f-4993-8085-d9784db52274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5d91048-ca5a-4408-80fc-6aa965afc1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Add
            ...
        </value>
      <webElementGuid>b7c7b469-48d4-4fe7-9e3a-bad8dbab8e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetedIndications&quot;)</value>
      <webElementGuid>abc64f45-dfc1-4250-b90b-eac9ef895362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='targetedIndications']</value>
      <webElementGuid>b355bde6-451c-4375-af6a-0267f94d06e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div[3]/div[2]/umb-property[2]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/button</value>
      <webElementGuid>3828c2ab-54a8-456d-84e6-5490e7a923e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Property Actions'])[2]/following::button[1]</value>
      <webElementGuid>776a980c-cd29-4b62-a1c7-e60c8b654ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[2]</value>
      <webElementGuid>99f7f6f6-70aa-4f71-b2af-44161f26319d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//umb-property[2]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/button</value>
      <webElementGuid>4c23d7ad-a75a-468a-9f02-fcac7d7fa9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'targetedIndications' and (text() = '
            Add
            ...
        ' or . = '
            Add
            ...
        ')]</value>
      <webElementGuid>cfd31795-aca8-4591-a8ef-2c4ca97e536f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
