<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Web Article Name_headerName</name>
   <tag></tag>
   <elementGuidId>012921b2-ee43-4332-a945-18e922cde914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headerName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5701697-9622-4a28-9414-7dd592432c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element</name>
      <type>Main</type>
      <value>editor-name-field</value>
      <webElementGuid>55887600-a9c3-4ad5-ad3e-6bc8200d4b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1abf90f-7bb1-4cd8-8c6d-d6806f2b4218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-editor-header__name-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-val-server-field</value>
      <webElementGuid>3266dbf6-375e-4b85-aa45-3ba5173781a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>1fd9b48f-73f7-4e2b-a8d9-b9dee4e0f8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>headerName</value>
      <webElementGuid>1582e99c-91e3-4cd2-8bde-28b7fdd3bd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerName</value>
      <webElementGuid>5506c04e-041a-4709-a54c-d6e563e25747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>7a5d427c-7ad3-4705-aaea-7d203294eee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'name-is-empty': $parent.name===null || $parent.name===''}</value>
      <webElementGuid>bbb4af0b-f0bd-40ef-92e6-32c319ce7174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>nameDisabled</value>
      <webElementGuid>2277f91e-8921-4e85-8e11-cf4f74cf8aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>nameReadonly</value>
      <webElementGuid>92dc1e79-b7a7-4db1-9503-6a1f47f745dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focus-on-filled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51757649-2a54-4d73-9076-919937ded9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server-field</name>
      <type>Main</type>
      <value>Variants[0].Name</value>
      <webElementGuid>c4d14582-ed34-4d50-b8b2-93f6f0cd32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69b70867-a951-42ac-bfd6-0a49298e8de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5c1c60e-2f10-441f-9487-010b92e9b8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>35acb0ae-9434-4a93-8a7e-26a9aaba850d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>aa54cc6e-d565-4aab-a9a8-1aa429296ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a name...</value>
      <webElementGuid>81f4ac3e-eaed-4135-a339-f302cbc3b4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerName&quot;)</value>
      <webElementGuid>2eb63e72-ee80-4571-841f-5aa4e12aae7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headerName']</value>
      <webElementGuid>3f2c8d3a-4e3a-4168-a4af-0a67298bff19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nameField']/div[2]/ng-form/input</value>
      <webElementGuid>f49afe00-7cc6-4a0b-99d6-d2d8ba77e071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b3e00470-20fb-46a0-be2c-0e21bd639000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'headerName' and @id = 'headerName' and @placeholder = 'Enter a name...']</value>
      <webElementGuid>b6a776a4-15f8-4819-86ae-512714871672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
