<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date the article was published_datepicker</name>
   <tag></tag>
   <elementGuidId>a7a82e07-c1bc-41f1-818e-9c7fa3908f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePublished']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datePublished</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>687459eb-4aa6-4934-8fee-44859a2fad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4d1b632-8738-483d-a2f4-b818d2b16cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>7a82e9e3-01b9-4008-8a6e-84d01fb5f6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePublished</value>
      <webElementGuid>fb31fb58-97d2-47bb-9f59-5089d2c7d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.datetimePickerValue</value>
      <webElementGuid>286d67f3-1a6e-4607-a469-6becea2a5aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>inputChanged()</value>
      <webElementGuid>b0e393a1-f4cd-4845-8a49-18cde6b8a918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>model.validation.mandatory</value>
      <webElementGuid>2728f561-557a-492b-89ae-c37cdb76a2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>e85374f1-4d05-4f28-8c4a-1efafa6ca697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepickerinput ng-pristine ng-untouched ng-valid-val-server ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>de8d8c91-2371-4fe8-9fc2-eef9b2a4a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ef9c3095-dd3a-4f7f-a429-63a5bcf1fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>49fe33a9-0c5b-48b2-8335-75bb3aacd88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5400f94f-0fed-4f78-b860-4a1d852104f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePublished&quot;)</value>
      <webElementGuid>84d7d934-715a-4c86-b3bb-bf90f25af382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePublished']</value>
      <webElementGuid>21f6bfde-4cef-4123-b95f-4ef0d2775752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepickerdatePublished']/umb-date-time-picker/ng-transclude/div/input</value>
      <webElementGuid>9ce4fe29-56ad-42e1-a02d-c982e5156b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a2b555a0-cb55-4dc0-9842-3f9a76b205ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepicker' and @id = 'datePublished']</value>
      <webElementGuid>f0d51f7a-a7d6-4512-b1ec-abe803963276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
