<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address to the article_textbox</name>
   <tag></tag>
   <elementGuidId>5d895275-a682-4eb5-a1a8-31093ed74f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#urlAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f6aa10f-2791-4d3c-a272-914a4222d7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17aec58e-e355-4209-b5e6-3133f5c3acb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlAddress</value>
      <webElementGuid>8bcee8fd-4aa1-4d37-86a1-4ebef04a658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8340471b-aeba-43da-8314-4c5fc87cdc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.value</value>
      <webElementGuid>c8ae8be0-0c0e-49a7-847f-a21ec0a9e353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>umb-property-editor umb-textstring textstring ng-pristine ng-untouched ng-valid-val-server ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>08d0a292-9492-4923-97ff-50757d4490f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val-server</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>21d7c3c9-435d-48f2-a279-4052743bb435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>model.validation.mandatory</value>
      <webElementGuid>8d4bee87-bc94-4cb6-a2b2-c6c9b1e6be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf6a1d8e-99bb-4d57-974d-cf03f8158c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57509f74-eb74-493c-b1d8-106317f1cc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d661afa-f3af-4f4e-a80c-e333a03597a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>change()</value>
      <webElementGuid>6a81f473-903d-4cfd-ba0a-b6ceb60b07cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e035531b-2891-4c0c-9a67-4564388ab514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>36e0f008-2a2a-45d5-b5a6-fc5feaaa66e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlAddress&quot;)</value>
      <webElementGuid>e44c1054-5a61-4a63-b061-38d762d98c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlAddress']</value>
      <webElementGuid>38f92d8f-ac99-4a83-9f0a-f5c63f8d12b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentcolumn']/div/div/div/div/form/div/umb-variant-content-editors/div/div/umb-variant-content/div/div/div/div[2]/div/div[2]/div/div/div/div/div/ng-form/div/div/umb-property[3]/div/ng-form/div/div[2]/div[2]/div/div/div/div/ng-form/input</value>
      <webElementGuid>6e61e0ca-c859-4427-b15d-bbd611364d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ng-form/input</value>
      <webElementGuid>f25cf26c-e473-4dcf-89f1-fbd7e809d980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'urlAddress' and @name = 'textbox']</value>
      <webElementGuid>d0b9e4bf-4cd6-48ca-8f4f-5cbe38ace4e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
